package TamanBermain.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Area;
  private ConceptPresentation props_TamanBermain;
  private ConceptPresentation props_restoran;
  private ConceptPresentation props_toko;
  private ConceptPresentation props_venue;
  private ConceptPresentation props_wahana;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Area:
        if (props_Area == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Area");
          props_Area = cpb.create();
        }
        return props_Area;
      case LanguageConceptSwitch.TamanBermain:
        if (props_TamanBermain == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("TamanBermain");
          props_TamanBermain = cpb.create();
        }
        return props_TamanBermain;
      case LanguageConceptSwitch.restoran:
        if (props_restoran == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("restoran");
          props_restoran = cpb.create();
        }
        return props_restoran;
      case LanguageConceptSwitch.toko:
        if (props_toko == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("toko");
          props_toko = cpb.create();
        }
        return props_toko;
      case LanguageConceptSwitch.venue:
        if (props_venue == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("venue");
          props_venue = cpb.create();
        }
        return props_venue;
      case LanguageConceptSwitch.wahana:
        if (props_wahana == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("wahana");
          props_wahana = cpb.create();
        }
        return props_wahana;
    }
    return null;
  }
}
