package TamanBermain.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Area = 0;
  public static final int TamanBermain = 1;
  public static final int restoran = 2;
  public static final int toko = 3;
  public static final int venue = 4;
  public static final int wahana = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x5194acc1bbd04011L, 0x97f4d074d6446485L);
    builder.put(0x755d40d61b7b51d8L, Area);
    builder.put(0x755d40d61b7b51cfL, TamanBermain);
    builder.put(0x755d40d61b7ce682L, restoran);
    builder.put(0x755d40d61b7ce68bL, toko);
    builder.put(0x755d40d61b7b51e2L, venue);
    builder.put(0x755d40d61b7ce679L, wahana);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
