package TamanBermain.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptArea = createDescriptorForArea();
  /*package*/ final ConceptDescriptor myConceptTamanBermain = createDescriptorForTamanBermain();
  /*package*/ final ConceptDescriptor myConceptrestoran = createDescriptorForrestoran();
  /*package*/ final ConceptDescriptor myConcepttoko = createDescriptorFortoko();
  /*package*/ final ConceptDescriptor myConceptvenue = createDescriptorForvenue();
  /*package*/ final ConceptDescriptor myConceptwahana = createDescriptorForwahana();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptArea, myConceptTamanBermain, myConceptrestoran, myConcepttoko, myConceptvenue, myConceptwahana);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Area:
        return myConceptArea;
      case LanguageConceptSwitch.TamanBermain:
        return myConceptTamanBermain;
      case LanguageConceptSwitch.restoran:
        return myConceptrestoran;
      case LanguageConceptSwitch.toko:
        return myConcepttoko;
      case LanguageConceptSwitch.venue:
        return myConceptvenue;
      case LanguageConceptSwitch.wahana:
        return myConceptwahana;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForArea() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TamanBermain", "Area", 0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7b51d8L);
    b.class_(false, false, false);
    b.origin("r:bb0752e7-427e-4a1a-bdf9-8c1609a0e02b(TamanBermain.structure)/8456986963599905240");
    b.version(3);
    b.property("luas", 0x755d40d61b7b51ddL).type(PrimitiveTypeId.INTEGER).origin("8456986963599905245").done();
    b.property("nama", 0x755d40d61b8580ddL).type(PrimitiveTypeId.STRING).origin("8456986963600572637").done();
    b.aggregate("venues", 0x755d40d61b7b51dfL).target(0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7b51e2L).optional(true).ordered(true).multiple(true).origin("8456986963599905247").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTamanBermain() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TamanBermain", "TamanBermain", 0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7b51cfL);
    b.class_(false, false, true);
    b.origin("r:bb0752e7-427e-4a1a-bdf9-8c1609a0e02b(TamanBermain.structure)/8456986963599905231");
    b.version(3);
    b.property("nama", 0x755d40d61b8580adL).type(PrimitiveTypeId.STRING).origin("8456986963600572589").done();
    b.aggregate("areas", 0x755d40d61b7b51d4L).target(0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7b51d8L).optional(true).ordered(true).multiple(true).origin("8456986963599905236").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForrestoran() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TamanBermain", "restoran", 0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7ce682L);
    b.class_(false, false, false);
    // extends: TamanBermain.structure.venue
    b.super_(0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7b51e2L);
    b.origin("r:bb0752e7-427e-4a1a-bdf9-8c1609a0e02b(TamanBermain.structure)/8456986963600008834");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorFortoko() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TamanBermain", "toko", 0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7ce68bL);
    b.class_(false, false, false);
    // extends: TamanBermain.structure.venue
    b.super_(0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7b51e2L);
    b.origin("r:bb0752e7-427e-4a1a-bdf9-8c1609a0e02b(TamanBermain.structure)/8456986963600008843");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForvenue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TamanBermain", "venue", 0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7b51e2L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:bb0752e7-427e-4a1a-bdf9-8c1609a0e02b(TamanBermain.structure)/8456986963599905250");
    b.version(3);
    b.property("kapasitas", 0x755d40d61b7b51e6L).type(PrimitiveTypeId.INTEGER).origin("8456986963599905254").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForwahana() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TamanBermain", "wahana", 0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7ce679L);
    b.class_(false, false, false);
    // extends: TamanBermain.structure.venue
    b.super_(0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7b51e2L);
    b.origin("r:bb0752e7-427e-4a1a-bdf9-8c1609a0e02b(TamanBermain.structure)/8456986963600008825");
    b.version(3);
    b.property("durasi", 0x755d40d61b8580d0L).type(PrimitiveTypeId.INTEGER).origin("8456986963600572624").done();
    return b.create();
  }
}
