package TamanBermain.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class toko_Constraints extends BaseConstraintsDescriptor {
  /*package*/ toko_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.toko$D9, initContext);
    record(new Kapasitas_PD(this));
  }

  /*package*/ static final class Kapasitas_PD extends BasePropertyConstraintsDescriptor {
    public Kapasitas_PD(ConstraintsDescriptor container) {
      super(PROPS.kapasitas$drZ4, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:60d2446b-9fea-46aa-883b-998d392c2085(TamanBermain.constraints)", "8456986963600436163"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue > 0;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept toko$D9 = MetaAdapterFactory.getConcept(0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7ce68bL, "TamanBermain.structure.toko");
  }

  private static final class PROPS {
    /*package*/ static final SProperty kapasitas$drZ4 = MetaAdapterFactory.getProperty(0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7b51e2L, 0x755d40d61b7b51e6L, "kapasitas");
  }
}
