package TamanBermain.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class wahana_Constraints extends BaseConstraintsDescriptor {
  /*package*/ wahana_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.wahana$c5, initContext);
    record(new Durasi_PD(this));
    record(new Kapasitas_PD(this));
  }

  /*package*/ static final class Durasi_PD extends BasePropertyConstraintsDescriptor {
    public Durasi_PD(ConstraintsDescriptor container) {
      super(PROPS.durasi$GftV, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:60d2446b-9fea-46aa-883b-998d392c2085(TamanBermain.constraints)", "8456986963600323517"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 10 && propertyValue <= 30;

    }
  }
  /*package*/ static final class Kapasitas_PD extends BasePropertyConstraintsDescriptor {
    public Kapasitas_PD(ConstraintsDescriptor container) {
      super(PROPS.kapasitas$Ga4$, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:60d2446b-9fea-46aa-883b-998d392c2085(TamanBermain.constraints)", "8456986963600400474"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 50 && propertyValue <= 100;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept wahana$c5 = MetaAdapterFactory.getConcept(0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7ce679L, "TamanBermain.structure.wahana");
  }

  private static final class PROPS {
    /*package*/ static final SProperty durasi$GftV = MetaAdapterFactory.getProperty(0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7ce679L, 0x755d40d61b7ce67fL, "durasi");
    /*package*/ static final SProperty kapasitas$Ga4$ = MetaAdapterFactory.getProperty(0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7ce679L, 0x755d40d61b7ce67dL, "kapasitas");
  }
}
