package TamanBermain.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Area_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new TamanBermain_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new restoran_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new toko_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new wahana_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7b51d8L), MetaIdFactory.conceptId(0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7b51cfL), MetaIdFactory.conceptId(0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7ce682L), MetaIdFactory.conceptId(0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7ce68bL), MetaIdFactory.conceptId(0x5194acc1bbd04011L, 0x97f4d074d6446485L, 0x755d40d61b7ce679L)).seal();
}
